### ISSUE TITLE
New video

### ISSUE THREAD

**Issue by JuandGirald** [jlmonroy13/brainstutor-client#35]
Add the new video in the home and "como funciona" page

<script src="https://fast.wistia.com/embed/medias/031ny7tr3t.jsonp" async></script><script src="https://fast.wistia.com/assets/external/E-v1.js" async></script><div class="wistia_responsive_padding" style="padding:56.25% 0 0 0;position:relative;"><div class="wistia_responsive_wrapper" style="height:100%;left:0;position:absolute;top:0;width:100%;"><div class="wistia_embed wistia_async_031ny7tr3t videoFoam=true" style="height:100%;width:100%">&nbsp;</div></div></div>

**Comment by Kevanz10** [comment]
mAMAMLO

2017-05-07 23:54 GMT-05:00 Jorge Luis Monroy Herrera <
notifications@github.com>:
